### ISSUE TITLE
Blitzed Grabber

### ISSUE THREAD

**Issue by StvnedEagle1337** [HideakiAtsuyo/Leaked0-List-2022#1]
Bros cracking a file thats not protected, and has no obfuscation 💀

**Comment by HideakiAtsuyo** [comment]
> Bros cracking a file thats not protected, and has no obfuscation 💀

Not my fault if you was not able to protect correctly the """v1""" and now don't protect it at all because you know you are not skilled enought to do something :joy:

**Comment by HideakiAtsuyo** [comment]
Hecker I hope you will not c/p it too much :(

![](https://i.imgur.com/b5zxMZs.png)
