### ISSUE TITLE
BoostNation Discord Tools (Boost bot tool, Nitro Redeemer, VCC Gen Tool, Promo Code Gen)

### ISSUE THREAD

**Issue by diary001** [HideakiAtsuyo/Leaked0-List-2022#2]
im not sure if these tools were custom made but these are all the tools you need to sell and automate discord server boosts and they sell these tools for $2000+ it would be nice to see them get leaked. if you need a link to their discord or website lmk

**Comment by master7720** [comment]
could you link there website?

**Comment by HideakiAtsuyo** [comment]
> im not sure if these tools were custom made but these are all the tools you need to sell and automate discord server boosts and they sell these tools for $2000+ it would be nice to see them get leaked. if you need a link to their discord or website lmk

Discord: Hideaki#5550
