### ISSUE TITLE
Blitzed Grabber 

### ISSUE THREAD

**Issue by 0verp0wer** [HideakiAtsuyo/Leaked0-List-2022#3]
You can leak the latest version of the grabber?

**Comment by HideakiAtsuyo** [comment]
> You can leak the latest version of the grabber?

Which version it is ? I only have V12

**Comment by 0verp0wer** [comment]
> > You can leak the latest version of the grabber?
> 
> Which version it is ? I only have V12

Yeah Is the v12,can you leak It?

**Comment by HideakiAtsuyo** [comment]
> > > You can leak the latest version of the grabber?
> > 
> > 
> > Which version it is ? I only have V12
> 
> Yeah Is the v12,can you leak It?

It's useless nothing change like other versions of stuff he "make" he didn't made anything on it

**Comment by 0verp0wer** [comment]
> > > > You can leak the latest version of the grabber?
> > > 
> > > 
> > > Which version it is ? I only have V12
> > 
> > 
> > Yeah Is the v12,can you leak It?
> 
> It's useless nothing change like other versions of stuff he "make" he didn't made anything on it

oh ok,I wanted to have it because the version you released yourself is the v2 and now we are at v12 so I thought they had fixated important bugs and even more

**Comment by HideakiAtsuyo** [comment]
> > > > > You can leak the latest version of the grabber?
> > > > 
> > > > 
> > > > Which version it is ? I only have V12
> > > 
> > > 
> > > Yeah Is the v12,can you leak It?
> > 
> > 
> > It's useless nothing change like other versions of stuff he "make" he didn't made anything on it
> 
> oh ok,I wanted to have it because the version you released yourself is the v2 and now we are at v12 so I thought they had fixated important bugs and even more

Keep in mind it's Stxned Eagle, He like to copy/paste, he can't write anything in the code you see, all his tools are using open-src or leaked stuff, the day he will make something like this himself I will trust god exist !😂 probably I will upload soon I don't know or see for something else ! :)

**Comment by 0verp0wer** [comment]
> > > > > > You can leak the latest version of the grabber?
> > > > > 
> > > > > 
> > > > > Which version it is ? I only have V12
> > > > 
> > > > 
> > > > Yeah Is the v12,can you leak It?
> > > 
> > > 
> > > It's useless nothing change like other versions of stuff he "make" he didn't made anything on it
> > 
> > 
> > oh ok,I wanted to have it because the version you released yourself is the v2 and now we are at v12 so I thought they had fixated important bugs and even more
> 
> Keep in mind it's Stxned Eagle, He like to copy/paste, he can't write anything in the code you see, all his tools are using open-src or leaked stuff, the day he will make something like this himself I will trust god exist !😂 probably I will upload soon I don't know or see for something else ! :)

Ok, thank you so much
