### ISSUE TITLE
Yo i would like to get a leak of the new "ss" method

### ISSUE THREAD

**Issue by schichingpingbing** [HideakiAtsuyo/Leaked0-List-2022#6]
Its called screenshare method and its being sold for 120 dollars i want it leaked cuz i think somethings not right thank you for responding or replying :)

**Comment by HideakiAtsuyo** [comment]
> Its called screenshare method and its being sold for 120 dollars i want it leaked cuz i think somethings not right thank you for responding or replying :)

Hello, be more precise I can't guess everything, where is it from ? What does it do ? Etc.. thanks :)

**Comment by popcrocks** [comment]
> > Its called screenshare method and its being sold for 120 dollars i want it leaked cuz i think somethings not right thank you for responding or replying :)
> 
> Hello, be more precise I can't guess everything, where is it from ? What does it do ? Etc.. thanks :)

pretty sure he is talking about a roblox beaming method. not too sure though

**Comment by HideakiAtsuyo** [comment]
> > > Its called screenshare method and its being sold for 120 dollars i want it leaked cuz i think somethings not right thank you for responding or replying :)
> > 
> > 
> > Hello, be more precise I can't guess everything, where is it from ? What does it do ? Etc.. thanks :)
> 
> pretty sure he is talking about a roblox beaming method. not too sure though

Then come back when you will know what you are talking about with details thanks ! Because I can't guess everything sadly..

**Comment by HideakiAtsuyo** [comment]
Not enough details to continue.
